### ISSUE TITLE
Gem won't install.  Says requires spork > 1.0rc0!?

### ISSUE THREAD

**Issue by noctivityinc** [sporkrb/spork-rails#15]
```
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/..
Bundler could not find compatible versions for gem "spork":
  In Gemfile:
    spork-rails (>= 0) ruby depends on
      spork (>= 1.0rc0) ruby

    guard-spork (>= 0) ruby depends on
      spork (0.9.2)
```

Any thoughts?

**Comment by radiohead** [comment]
Could you please be more specific? I've tried to reproduce this one by creating a Rails app and adding **guard-spork** and **spork-rails** to Gemfile, but I haven't got any errors.

**Comment by noctivityinc** [comment]
Well here is my gemfile, other than that what else would you like to know?  It's a Rails 3.2.11 app on Ruby 1.9.3

```
source 'https://rubygems.org'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'bootstrap-sass', '~> 2.2.2.0'
  gem 'compass-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem "haml-rails"
gem 'thin'
gem "nifty-generators", :group => :development
gem 'simple_form'
gem 'nokogiri'
gem 'devise'
gem 'country_select'
gem 'activeadmin'
gem "meta_search",    '>= 1.1.0.pre'
gem "paperclip", "~> 3.0"
gem "paperclip-aws", "~> 1.6.7"
gem 'aws-sdk'
gem 'wicked'
gem 'redcarpet'
gem 'acts-as-taggable-on', '~> 2.3.1'
gem 'faker'
gem "airbrake"


# To use debugger
group :development do
  gem 'seed_dump'
  gem 'certified'
  # gem 'spork-rails'
  gem 'guard-spork'

  gem 'jazz_hands'
  # gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
end

group :test, :development do
  gem "rspec-rails"
  gem 'factory_girl_rails'
  gem 'debugger'

  gem 'annotate'

  # required to convert devise views to haml
  # https://github.com/plataformatec/devise/wiki/How-To%3a-Create-Haml-and-Slim-Views
  # for i in `find app/views/devise -name '*.erb'` ; do html2haml -e $i ${i%erb}haml ; rm $i ; done
  gem 'ruby_parser'
  gem 'html2haml', :git => "https://github.com/haml/html2haml.git"
end

group :test do
  gem 'capybara'
  gem "capybara-webkit"
  gem 'launchy'
  gem 'guard-rspec'
  gem 'database_cleaner'
  gem 'rb-fsevent', '~> 0.9.1'
  gem 'terminal-notifier-guard'
  gem 'valid_attribute'
  gem 'database_cleaner'
  gem 'fuubar'

end

gem "mocha", :group => :test
```

**Comment by radiohead** [comment]
OK, I'll try to reproduce this bug. In the meantime - can you remove **spork-rails**, **spork** and **guard-spork** manually and run **bundle install**?

**Comment by radiohead** [comment]
I was unable to reproduce your problem with the given gemset. I think there's a problem in your environment, consider using a fresh gemset.

**Comment by shime** [comment]
Same issue. This is how you reproduce it. First, use **spork** and **guard-spork** like so:

```
gem 'spork'
gem 'guard-spork'
```

`bundle && bundle show spork` should give you the `0.9.2` version since that's the latest stable and [guard-spork is depending on >= 0.8.4](https://github.com/guard/guard-spork/blob/master/guard-spork.gemspec#L20).

---

If you, however, want to update your Gemfile to use **spork-rails** after that, you would replace the above lines with something like this.

```
gem 'spork-rails'
gem 'guard-spork'
```

`bundle` now fails with

```
Bundler could not find compatible versions for gem "spork":
  In Gemfile:
    spork-rails (>= 0) ruby depends on
      spork (>= 1.0rc0) ruby

    spork (0.9.2)
```

---

You can resolve this by specifying the version of **spork** in your Gemfile.

```
gem 'spork', '1.0.0rc0'
gem 'spork-rails'
gem 'guard-spork'
```

Running `bundle update spork` resolves the dependency issue, but now I'm experiencing weird `Errno::ENOENT` issue when running `bundle exec spork rspec --bootstrap`:

```
No such file or directory - /home/hrvoje/.rvm/gems/ruby-1.9.3-p385/gems/spork-1.0.0rc0/lib/spork/../../assets/bootstrap.rb (Errno::ENOENT)
/home/hrvoje/.rvm/gems/ruby-1.9.3-p385/gems/spork-1.0.0rc0/lib/spork/test_framework.rb:99:in `read'
/home/hrvoje/.rvm/gems/ruby-1.9.3-p385/gems/spork-1.0.0rc0/lib/spork/test_framework.rb:99:in `bootstrap'
/home/hrvoje/.rvm/gems/ruby-1.9.3-p385/gems/spork-1.0.0rc0/lib/spork/runner.rb:64:in `run'
/home/hrvoje/.rvm/gems/ruby-1.9.3-p385/gems/spork-1.0.0rc0/lib/spork/runner.rb:10:in `run'
/home/hrvoje/.rvm/gems/ruby-1.9.3-p385/gems/spork-1.0.0rc0/bin/spork:10:in `<top (required)>'
/home/hrvoje/.rvm/gems/ruby-1.9.3-p385/bin/spork:19:in `load'
/home/hrvoje/.rvm/gems/ruby-1.9.3-p385/bin/spork:19:in `<main>'
/home/hrvoje/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `eval'
/home/hrvoje/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by noctivityinc** [comment]
Yes.  Exactly.  Those were the steps that led to my issue as well.

Joshua Lippiner  
.:t 704.323.5661
.:e jlippiner@noctivity.com

**Comment by lulalala** [comment]
+1, I upgraded from spork to spork-rails and it is complaining `guard-spork (~> 1.5.0) ruby depends on spork (0.9.2)`

**Comment by ijxsid** [comment]
I am having the same error while installing spork-rails on rails 4 

``` bash
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "spork":
  In Gemfile:
    spork-rails (>= 0) ruby depends on
      spork (>= 1.0rc0) ruby

    guard-spork (>= 0) ruby depends on
      spork (0.9.2)


```

Then i deleted "spork-rails" from the gemfile and added only "spork", it installed correctly, but i couldn't run spork server, similar error as described here :https://github.com/sporkrb/spork/issues/223
That thread concluded that we should use the git repo of the main "spork-rails" repo, then i added the git repo to the gemfile:

``` ruby
source 'https://rubygems.org'

ruby '2.0.0'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'


# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

# Faker, a port of Data::Faker from Perl, is used to easily generate 
# fake data: names, addresses, phone numbers, etc.
gem "faker", "~> 1.2.0"

# Twitter's Bootstrap, converted to Sass and ready to drop into Rails or Compass
gem "bootstrap-sass", "~> 2.3.2.1"

# will_paginate provides a simple API for performing paginated queries with 
# Active Record, DataMapper and Sequel, and includes helpers for rendering 
# pagination links in Rails, Sinatra and Merb web apps.
gem "will_paginate", "~> 3.0.4"

# Hooks into will_paginate to format the html to match Twitter Bootstrap styling.
gem "bootstrap-will_paginate", "~> 0.0.9"

# Using the multi-threaded puma app server
gem 'puma'

# Using Haml preprocessor
gem 'haml-rails'

group :test, :development do
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'guard-spork'
  gem 'spork-rails', git: 'https://github.com/sporkrb/spork-rails.git'
  gem 'childprocess'



end

group :test do
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem "libnotify", "~> 0.8.1"
  # gem 'launchy', '2.1.0'
  # gem 'rb-fsevent', '0.9.1', :require => false
  # gem 'growl', '1.0.3'
end

group :production do
  gem "pg", "~> 0.16.0"
end
```

But i ended with the same error as i started. Any thought on how to resolve the dependencies on spork gem?

**Comment by exocode** [comment]
same here

**Comment by lulalala** [comment]
@klangfeld @FalloutX I think my fork fixed this. You may want to try.

**Comment by sahilm** [comment]
I've released spork-rails 4.0.0 to RubyGems. Please try updating your spork-rails bundle.

**Comment by hphan62** [comment]
Here what I included in my Gemfile
 .....
  gem 'spork','1.0.0rc0'
  gem 'guard-spork'
  gem 'spork-rails'
....
spork now worked fine....THANKS A LOT.

Here is my Gem list:
$ gem list

**\* LOCAL GEMS ***

actionmailer (4.1.0)
actionpack (4.1.0)
actionview (4.1.0)
activemodel (4.1.0)
activerecord (4.1.0)
activesupport (4.1.0)
addressable (2.3.6)
archive-tar-minitar (0.5.2)
arel (5.0.1.20140414130214)
bigdecimal (1.1.0)
builder (3.2.2)
bundler (1.6.2)
capybara (2.2.1, 1.1.2)
celluloid (0.15.2)
celluloid-io (0.15.0)
childprocess (0.5.3)
coderay (1.1.0)
coffee-rails (4.0.1)
coffee-script (2.2.0)
coffee-script-source (1.7.0)
columnize (0.3.6)
diff-lcs (1.2.5)
erubis (2.7.0)
excon (0.33.0)
execjs (2.0.2)
ffi (1.9.3 x86-mingw32)
formatador (0.2.4)
git (1.2.6)
guard (2.6.0)
guard-rspec (4.2.8)
guard-spork (1.5.1)
heroku (3.6.0)
heroku-api (0.3.18)
hike (1.2.3)
i18n (0.6.9)
io-console (0.3)
jbuilder (2.0.6)
jquery-rails (3.1.0)
json (1.8.1, 1.5.5)
launchy (2.4.2)
linecache19 (0.5.12)
listen (2.7.4)
lumberjack (1.0.5)
mail (2.5.4)
method_source (0.8.2)
mime-types (1.25.1)
mini_portile (0.5.3)
minitest (5.3.3, 5.3.1, 2.5.1)
multi_json (1.9.3, 1.9.2)
netrc (0.7.7)
nio4r (1.0.0)
nokogiri (1.6.1 x86-mingw32)
pg (0.17.1 x86-mingw32)
polyglot (0.3.4)
pry (0.9.12.6 i386-mingw32)
rack (1.5.2)
rack-test (0.6.2)
rails (4.1.0)
railties (4.1.0)
rake (10.3.1, 0.9.2.2)
rb-fchange (0.0.6)
rb-fsevent (0.9.4)
rb-inotify (0.9.4)
rb-notifu (0.0.4)
rb-readline (0.5.1)
rdoc (4.1.1, 3.9.5)
rest-client (1.6.7)
rspec (2.14.1)
rspec-core (2.14.8)
rspec-expectations (2.14.5)
rspec-mocks (2.14.6)
rspec-rails (2.14.2)
ruby-debug-base19 (0.11.26)
ruby-debug-ide19 (0.4.12)
ruby-debug19 (0.11.6)
ruby_core_source (0.1.5)
rubyzip (1.1.3)
sass (3.2.19)
sass-rails (4.0.3)
sdoc (0.4.0)
selenium-webdriver (2.41.0)
slop (3.5.0)
spork (1.0.0rc4 x86-mingw32, 1.0.0rc0 x86-mingw32, 0.9.2)
spork-rails (4.0.0)
sprockets (2.12.1, 2.11.0)
sprockets-rails (2.1.3)
sqlite3 (1.3.9 x86-mingw32)
thor (0.19.1)
thread_safe (0.3.3)
tilt (1.4.1)
timers (1.1.0)
treetop (1.4.15)
turbolinks (2.2.2)
tzinfo (1.1.0)
tzinfo-data (1.2014.2)
uglifier (2.5.0)
websocket (1.0.7)
win32-process (0.7.4)
win32console (1.3.2 x86-mingw32)
xpath (2.0.0, 0.1.4)
